#!/usr/bin/env python

import vrep
import time
import socket
import sys
SERVER_IP = "192.168.2.123"
SERVER_PORT = 8888

print("Starting socket: TCP...")
server_addr = (SERVER_IP, SERVER_PORT)
socket_tcp = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

#tmp1 = '1'
#tmp2 = '150'
#command = tmp1 +' ' + tmp2
#print command
#tmp3 = command.split()
#print  tmp3[0]
#print  tmp3[1]
#time.sleep(30)	

while True:
    try:
        print("Connecting to server @ %s:%d..." %(SERVER_IP, SERVER_PORT))
        socket_tcp.connect(server_addr)
        break
    except Exception:
        print("Can't connect to server,try it latter!")
        time.sleep(1)
        continue	


vrep.simxFinish(-1)
clientID = vrep.simxStart('127.0.0.1', 19997, True, True, 5000, 5)#start connect

if clientID!=-1:
	print 'Connected to remote API server'
	vrep.simxStartSimulation(clientID,vrep.simx_opmode_oneshot_wait) #start simulation
	res,m1Dyn = vrep.simxGetObjectHandle(clientID, "m1", vrep.simx_opmode_oneshot_wait)
	res,m2Dyn = vrep.simxGetObjectHandle(clientID, "m2", vrep.simx_opmode_oneshot_wait)
	res,m3Dyn = vrep.simxGetObjectHandle(clientID, "m3", vrep.simx_opmode_oneshot_wait)
	res,m4Dyn = vrep.simxGetObjectHandle(clientID, "m4", vrep.simx_opmode_oneshot_wait)
	res,m5Dyn = vrep.simxGetObjectHandle(clientID, "m5", vrep.simx_opmode_oneshot_wait)


	res,m1Position = vrep.simxGetJointPosition(clientID, m1Dyn, vrep.simx_opmode_oneshot_wait)
	res,m2Position = vrep.simxGetJointPosition(clientID, m2Dyn, vrep.simx_opmode_oneshot_wait)
	res,m3Position = vrep.simxGetJointPosition(clientID, m3Dyn, vrep.simx_opmode_oneshot_wait)
	res,m4Position = vrep.simxGetJointPosition(clientID, m4Dyn, vrep.simx_opmode_oneshot_wait)
	res,m5Position = vrep.simxGetJointPosition(clientID, m5Dyn, vrep.simx_opmode_oneshot_wait)
	#print m1Position,m2Position,m3Position,m4Position,m5Position
	while 1:
		res,m1Position = vrep.simxGetJointPosition(clientID, m1Dyn, vrep.simx_opmode_streaming)
		res,m2Position = vrep.simxGetJointPosition(clientID, m2Dyn, vrep.simx_opmode_streaming)
		res,m3Position = vrep.simxGetJointPosition(clientID, m3Dyn, vrep.simx_opmode_streaming)
		res,m4Position = vrep.simxGetJointPosition(clientID, m4Dyn, vrep.simx_opmode_streaming)
		res,m5Position = vrep.simxGetJointPosition(clientID, m5Dyn, vrep.simx_opmode_streaming)
		angle1 = 150 + m1Position*180/3.14
		angle2 = 150 + m2Position*180/3.14
		angle3 = 150 + m3Position*180/3.14
		angle4 = 150 - m4Position*180/3.14
		angle5 = 150 + m5Position*180/3.14

		ID = '1'
		command = ID + ' ' + str(angle1)
		print command 
		socket_tcp.send(command)
		time.sleep(0.01)
		ID = '2'
		command = ID + ' ' + str(angle2)
		print command 
		socket_tcp.send(command)
		time.sleep(0.01)
		ID = '3'
		command = ID + ' ' + str(angle3)
		print command 
		socket_tcp.send(command)
		time.sleep(0.01)
		ID = '4'
		command = ID + ' ' + str(angle4)
		print command 
		socket_tcp.send(command)
		time.sleep(0.01)
		ID = '5'
		command = ID + ' ' + str(angle5)
		print command 
		socket_tcp.send(command)
		time.sleep(0.01)

		





